-- Reconcile timestamp defaults to match local schema (use CURRENT_TIMESTAMP(3))
ALTER TABLE `Module` MODIFY COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE `Topic` MODIFY COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE `Article` MODIFY COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE `MediaAsset` MODIFY COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE `NavMenu` MODIFY COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE `NavSubMenu` MODIFY COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE `Topic` MODIFY COLUMN `updatedAt` DATETIME(3) NOT NULL;
ALTER TABLE `Module` MODIFY COLUMN `updatedAt` DATETIME(3) NOT NULL;
ALTER TABLE `Article` MODIFY COLUMN `updatedAt` DATETIME(3) NOT NULL;
ALTER TABLE `NavMenu` MODIFY COLUMN `updatedAt` DATETIME(3) NOT NULL;
ALTER TABLE `NavSubMenu` MODIFY COLUMN `updatedAt` DATETIME(3) NOT NULL;
ALTER TABLE `ArticleSection` MODIFY COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE `ArticleSection` MODIFY COLUMN `updatedAt` DATETIME(3) NOT NULL;

-- Normalize nullable text columns to have DEFAULT NULL (no-op if already correct)
ALTER TABLE `Article` MODIFY COLUMN `summary` TEXT NULL DEFAULT NULL;
ALTER TABLE `Article` MODIFY COLUMN `seoDescription` TEXT NULL DEFAULT NULL;
ALTER TABLE `Article` MODIFY COLUMN `seoTitle` VARCHAR(191) NULL DEFAULT NULL;
ALTER TABLE `Article` MODIFY COLUMN `seoCanonicalUrl` VARCHAR(191) NULL DEFAULT NULL;
