-- Normalize DEFAULT NULL for nullable columns and harmonize enum defaults

-- ARTICLES
ALTER TABLE `Article` MODIFY COLUMN `scheduledAt` DATETIME(3) NULL DEFAULT NULL;
ALTER TABLE `Article` MODIFY COLUMN `seoCanonicalUrl` VARCHAR(191) NULL DEFAULT NULL;
ALTER TABLE `Article` MODIFY COLUMN `seoDescription` TEXT NULL DEFAULT NULL;
ALTER TABLE `Article` MODIFY COLUMN `seoTitle` VARCHAR(191) NULL DEFAULT NULL;
ALTER TABLE `Article` MODIFY COLUMN `summary` TEXT NULL DEFAULT NULL;
ALTER TABLE `Article` MODIFY COLUMN `updatedBy` INT NULL DEFAULT NULL;
ALTER TABLE `Article` MODIFY COLUMN `status` ENUM('DRAFT','SCHEDULED','PUBLISHED','ARCHIVED') NOT NULL DEFAULT 'DRAFT';

-- MEDIA ASSET
ALTER TABLE `MediaAsset` MODIFY COLUMN `aiPrompt` TEXT NULL DEFAULT NULL;
ALTER TABLE `MediaAsset` MODIFY COLUMN `altText` VARCHAR(191) NULL DEFAULT NULL;
ALTER TABLE `MediaAsset` MODIFY COLUMN `caption` VARCHAR(191) NULL DEFAULT NULL;
ALTER TABLE `MediaAsset` MODIFY COLUMN `mimeType` VARCHAR(191) NULL DEFAULT NULL;
ALTER TABLE `MediaAsset` MODIFY COLUMN `width` INT NULL DEFAULT NULL;
ALTER TABLE `MediaAsset` MODIFY COLUMN `height` INT NULL DEFAULT NULL;
ALTER TABLE `MediaAsset` MODIFY COLUMN `sizeBytes` INT NULL DEFAULT NULL;
ALTER TABLE `MediaAsset` MODIFY COLUMN `createdByUserId` INT NULL DEFAULT NULL;

-- MODULE
ALTER TABLE `Module` MODIFY COLUMN `description` TEXT NULL DEFAULT NULL;
ALTER TABLE `Module` MODIFY COLUMN `icon` VARCHAR(191) NULL DEFAULT NULL;
ALTER TABLE `Module` MODIFY COLUMN `color` VARCHAR(191) NULL DEFAULT NULL;
ALTER TABLE `Module` MODIFY COLUMN `coverImage` VARCHAR(191) NULL DEFAULT NULL;
ALTER TABLE `Module` MODIFY COLUMN `createdBy` INT NULL DEFAULT NULL;
ALTER TABLE `Module` MODIFY COLUMN `updatedBy` INT NULL DEFAULT NULL;

-- TOPIC
ALTER TABLE `Topic` MODIFY COLUMN `description` TEXT NULL DEFAULT NULL;
ALTER TABLE `Topic` MODIFY COLUMN `icon` VARCHAR(191) NULL DEFAULT NULL;
ALTER TABLE `Topic` MODIFY COLUMN `color` VARCHAR(191) NULL DEFAULT NULL;
ALTER TABLE `Topic` MODIFY COLUMN `coverImage` VARCHAR(191) NULL DEFAULT NULL;
ALTER TABLE `Topic` MODIFY COLUMN `createdBy` INT NULL DEFAULT NULL;
ALTER TABLE `Topic` MODIFY COLUMN `updatedBy` INT NULL DEFAULT NULL;

-- NAV
ALTER TABLE `NavMenu` MODIFY COLUMN `description` TEXT NULL DEFAULT NULL;
ALTER TABLE `NavSubMenu` MODIFY COLUMN `description` TEXT NULL DEFAULT NULL;

-- SITE SETTINGS
ALTER TABLE `SiteSettings` MODIFY COLUMN `tagline` VARCHAR(191) NULL DEFAULT NULL;
ALTER TABLE `SiteSettings` MODIFY COLUMN `logoUrl` VARCHAR(191) NULL DEFAULT NULL;
ALTER TABLE `SiteSettings` MODIFY COLUMN `faviconUrl` VARCHAR(191) NULL DEFAULT NULL;
ALTER TABLE `SiteSettings` MODIFY COLUMN `metaDescription` TEXT NULL DEFAULT NULL;
ALTER TABLE `SiteSettings` MODIFY COLUMN `footerText` VARCHAR(191) NULL DEFAULT NULL;
ALTER TABLE `SiteSettings` MODIFY COLUMN `socialTwitter` VARCHAR(191) NULL DEFAULT NULL;
ALTER TABLE `SiteSettings` MODIFY COLUMN `socialLinkedin` VARCHAR(191) NULL DEFAULT NULL;
ALTER TABLE `SiteSettings` MODIFY COLUMN `socialYoutube` VARCHAR(191) NULL DEFAULT NULL;
ALTER TABLE `SiteSettings` MODIFY COLUMN `defaultOgImage` VARCHAR(191) NULL DEFAULT NULL;
ALTER TABLE `SiteSettings` MODIFY COLUMN `analyticsId` VARCHAR(191) NULL DEFAULT NULL;

-- USER role default harmonize
ALTER TABLE `User` MODIFY COLUMN `role` ENUM('ADMIN','SUPERADMIN') NOT NULL DEFAULT 'ADMIN';
